Django_V1.2/purchase_system/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.order_list, name='order_list'),
    path('new/', views.order_create, name='order_new'),
    path('edit/<int:id>/', views.order_update, name='order_edit'),
    path('delete/<int:id>/', views.order_delete, name='order_delete'),
    path('approve/<int:id>/', views.order_approve, name='order_approve'),
    path('disapprove/<int:id>/', views.order_disapprove, name='order_disapprove'),
    path('product-search/', views.product_search, name='product_search'),
]

Django_V1.2/purchase_system/purchase_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from accounts.views import profile_view
from .views import home  # Import the home view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),  # Use the home view for the root URL
    path('admin/users/', include('user_management.urls', namespace='admin_user_management')),
    path('admin/', admin.site.urls),    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', profile_view, name='profile'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'), 
    path('users/', include('user_management.urls', namespace='user_management')),  # Assuming there's a user_management.urls module
    path('projects/', include('Projects.urls')), 
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),# Make sure this is correct
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django_V1.2/purchase_system/user_management/urls.py
from django.urls import path
from . import views

app_name = 'user_management'

urlpatterns = [
    path('users/', views.user_list, name='user_list'),
    path('users/edit/<int:user_id>/', views.user_edit, name='user_edit'),
]

Django_V1.2/purchase_system/templates/Untitled-1.html
<h1>Welcome to the Purchase System</h1>
{% if user.is_authenticated %}
    <p>Hi Mr.{{ user.username }}! Welcome back. <br> {% now "F j, Y" %}.</p>
{% else %}
    <p>Welcome, guest! Consider <a href="{% url 'login' %}">logging in</a>. Today is {% now "F j, Y" %}.</p>
{% endif %}
<p>Choose an option:</p>
<ul>
    <li><a href="{% url 'products:list' %}">View Products</a></li>
    <li><a href="{% url 'orders:list' %}">View Orders</a></li>
    {% if user.is_superuser %}
        <li><a href="{% url 'user_management:user_list' %}">Manage Users</a></li>
    {% endif %}
</ul>

Django_V1.2/purchase_system/templates/home.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<p style="font:gray;">The dashboard goes here.</p>
{% endblock %}